package Presentacion.vistas.vistaCliente;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import Negocio.Cliente.TCliente;
import Presentacion.comandos.listadecomandos.ListaComandos;
import Presentacion.controlador.Controller;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USUARIO
 */
public class ClienteGUI extends javax.swing.JFrame {

	private static final String SEPARATOR = "-----------------------------------------";
    /**
     * Creates new form ClienteGUI
     */
    public ClienteGUI() {
    	this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/MotorLand.png")).getImage());
        initComponents();
    }

    private void limpiarComponentes(){
    	dniTF.setText("");
        domicilioTF.setText("");
        idTF.setText("");
        clienteTA.setText("");
        nombreTF.setText("");
        tarjetaTF.setText("");
    }
    
    public void muestra(TCliente ...t) {
    	for (TCliente tCliente : t) {
			clienteTA.append(tCliente.toString());
			clienteTA.append(System.getProperty("line.separator"));
			clienteTA.append(SEPARATOR + System.getProperty("line.separator"));
			
		}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        limpiarB = new javax.swing.JButton();
        idTF = new javax.swing.JTextField();
        nombreTF = new javax.swing.JTextField();
        dniTF = new javax.swing.JTextField();
        domicilioTF = new javax.swing.JTextField();
        tarjetaTF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clienteTA = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        altaB = new javax.swing.JButton();
        bajaB = new javax.swing.JButton();
        modificaB = new javax.swing.JButton();
        consultaB = new javax.swing.JButton();
        listarB = new javax.swing.JButton();
        clienteVipB = new javax.swing.JButton();
        volverB = new javax.swing.JButton();
        eliminaB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("ID:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("DNI:");

        jLabel4.setText("Domicilio:");

        jLabel5.setText("Tarjeta:");

        limpiarB.setText("Limpiar");
        limpiarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel5))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTF)
                    .addComponent(nombreTF)
                    .addComponent(dniTF)
                    .addComponent(domicilioTF)
                    .addComponent(tarjetaTF))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(limpiarB)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dniTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(domicilioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tarjetaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(limpiarB)
                .addGap(20, 20, 20))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        clienteTA.setEditable(false);
        clienteTA.setColumns(20);
        clienteTA.setRows(5);
        jScrollPane1.setViewportView(clienteTA);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        altaB.setText("Alta Cliente");
        altaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaBActionPerformed(evt);
            }
        });

        bajaB.setText("Baja Cliente");
        bajaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaBActionPerformed(evt);
            }
        });

        modificaB.setText("Modifica Cliente");
        modificaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaBActionPerformed(evt);
            }
        });

        consultaB.setText("Consulta Cliente");
        consultaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaBActionPerformed(evt);
            }
        });

        listarB.setText("Listar Clientes");
        listarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBActionPerformed(evt);
            }
        });

        clienteVipB.setBackground(new java.awt.Color(240, 240, 29));
        clienteVipB.setText("Cliente VIP");
        clienteVipB.setToolTipText("Muestra el cliente con el alquiler mas costoso.");
        clienteVipB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteVipBActionPerformed(evt);
            }
        });

        volverB.setText("Volver");
        volverB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBActionPerformed(evt);
            }
        });

        eliminaB.setText("Elimina Cliente");
        eliminaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(altaB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bajaB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(listarB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modificaB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(consultaB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(clienteVipB, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(volverB)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addComponent(clienteVipB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(altaB)
                        .addGap(18, 18, 18)
                        .addComponent(bajaB)
                        .addGap(18, 18, 18)
                        .addComponent(modificaB)
                        .addGap(18, 18, 18)
                        .addComponent(consultaB)
                        .addGap(18, 18, 18)
                        .addComponent(listarB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverB)
                    .addComponent(eliminaB))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaBActionPerformed
    	if(dniTF.getText().isEmpty() || domicilioTF.getText().isEmpty() || 
    			nombreTF.getText().isEmpty() || tarjetaTF.getText().isEmpty() ){
   		 	JOptionPane.showMessageDialog(this,"Faltan campos por rellenar", "Alta cliente", JOptionPane.ERROR_MESSAGE);
	   	}
	   	else{
	   		try {
		   		long tarjeta = Long.parseLong(tarjetaTF.getText());
		   		String nombre = nombreTF.getText();
		   		String domicilio = domicilioTF.getText();
		   		String dni = dniTF.getText();
		   		
		   		TCliente t = new TCliente(-1, nombre, dni, domicilio, tarjeta, true);
		   		
		   		Controller.getInstance().run(ListaComandos.NEGOCIOALTACLIENTE, t);
	   		}
	   		catch(NumberFormatException e) {
	   			JOptionPane.showMessageDialog(this,"Formato del campo incorrecto.", "Alta cliente", JOptionPane.ERROR_MESSAGE);
	   		}
	   		
   		}
    }//GEN-LAST:event_altaBActionPerformed

    private void bajaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaBActionPerformed
    	if(idTF.getText().isEmpty()){
    		JOptionPane.showMessageDialog(this,"El campo ID esta vacío.", "Baja cliente", JOptionPane.ERROR_MESSAGE);
    	}

    	else{
	   		int id =Integer.parseInt(idTF.getText());
	   		try {
		    	Controller.getInstance().run(ListaComandos.NEGOCIOBAJACLIENTE, id);
		    	
	   		}
	   		catch(NumberFormatException e) {
	   			JOptionPane.showMessageDialog(this,"Formato del campo ID incorrecto. Introduzca un numero entero positivo.", "Baja cliente", JOptionPane.ERROR_MESSAGE);
	   		}
	   		
	    	limpiarComponentes();

    	}
    }//GEN-LAST:event_bajaBActionPerformed

    private void modificaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificaBActionPerformed
    	if(dniTF.getText().isEmpty() && domicilioTF.getText().isEmpty() && nombreTF.getText().isEmpty() && 
    			tarjetaTF.getText().isEmpty()){
   		 	JOptionPane.showMessageDialog(this,"Campos vacíos. Rellene aquellos campos que desea modificar.", "Modificar cliente", 
   		 			JOptionPane.ERROR_MESSAGE);
	   	}

    	else{
    		if(idTF.getText().isEmpty()){
    			JOptionPane.showMessageDialog(this,"Introduzca el ID del cliente que quiere modificar.", "Modificar cliente", 
       		 			JOptionPane.ERROR_MESSAGE);
    		}
    		else {
    			try {
	    			int id = Integer.parseInt(idTF.getText());
	    			String nombre = nombreTF.getText();
	    			String dni = dniTF.getText();
	    			String domicilio = domicilioTF.getText();
	    			long tarjeta = Long.parseLong(tarjetaTF.getText());
	    			
			    	TCliente t = new TCliente(id, nombre, dni, domicilio, tarjeta, true);
			   		
			    	Controller.getInstance().run(ListaComandos.NEGOCIOMODIFICARCLIENTE, t);
			    	
    			}catch(NumberFormatException e) {
    				JOptionPane.showMessageDialog(this,"El formato de alguno de los campos es incorrecto.", "Modificar cliente", 
           		 			JOptionPane.ERROR_MESSAGE);
    			}
		    	
    		}
    	}
    }//GEN-LAST:event_modificaBActionPerformed

    private void consultaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaBActionPerformed
    	if(idTF.getText().isEmpty()){
    		JOptionPane.showMessageDialog(this,"Introduzca el ID del cliente que quiere consultar", "Consulta cliente",
    				JOptionPane.ERROR_MESSAGE);
    	}
  
    	else{
    		try {
		    	int id = Integer.parseInt(idTF.getText());
		    	if(id <= 0)
		    		throw new NumberFormatException();
		    	
		    	Controller.getInstance().run(ListaComandos.NEGOCIOCONSULTARCLIENTE, id);
		    	
    		}catch(NumberFormatException e) {
    			JOptionPane.showMessageDialog(this,"Formato del campo ID incorrecto. Introduzca un numero entero positivo.", "Consulta cliente",
        				JOptionPane.ERROR_MESSAGE);
    		}
	    	
    	}
    }//GEN-LAST:event_consultaBActionPerformed

    private void listarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBActionPerformed
        
    	Controller.getInstance().run(ListaComandos.NEGOCIOLISTACLIENTE, null);
    	
    }//GEN-LAST:event_listarBActionPerformed

    private void eliminaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaBActionPerformed
        int id;
        
        try {
        	if(idTF.getText().isEmpty())
        		JOptionPane.showMessageDialog(this,"Campo ID vacío.", "Elimina cliente",
        				JOptionPane.ERROR_MESSAGE);
        	else {
        		id = Integer.parseInt(idTF.getText());
        		
        		if(id <= 0)
        			throw new NumberFormatException(); 
        		
        		Controller.getInstance().run(ListaComandos.NEGOCIO_ELIMINA_CLIENTE, id);
        	}
        }
        catch(NumberFormatException e) {
        	JOptionPane.showMessageDialog(this,"Formato del campo ID incorrecto. Introduzca un numero entero positivo.", "Elimina cliente",
    				JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminaBActionPerformed

    private void clienteVipBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteVipBActionPerformed
    	int id;
        
        try {
        	if(idTF.getText().isEmpty())
        		JOptionPane.showMessageDialog(this,"Campo ID vacío.", "Consulta cliente VIP",
        				JOptionPane.ERROR_MESSAGE);
        	else {
        		id = Integer.parseInt(idTF.getText());
        		
        		if(id <= 0)
        			throw new NumberFormatException(); 
        		
        		Controller.getInstance().run(ListaComandos.NEGOCIOCLIENTEVIP, id);
        	}
        }
        catch(NumberFormatException e) {
        	JOptionPane.showMessageDialog(this,"Formato del campo ID incorrecto. Introduzca un numero entero positivo.", "Consulta cliente VIP",
    				JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_clienteVipBActionPerformed

    private void limpiarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarBActionPerformed
    	limpiarComponentes();
    	clienteTA.setText("");
    }//GEN-LAST:event_limpiarBActionPerformed

    private void volverBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBActionPerformed
    	Controller.getInstance().run(ListaComandos.CERRAR_VISTA_CLIENTE, null);
    }//GEN-LAST:event_volverBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaB;
    private javax.swing.JButton bajaB;
    private javax.swing.JTextArea clienteTA;
    private javax.swing.JButton clienteVipB;
    private javax.swing.JButton consultaB;
    private javax.swing.JTextField dniTF;
    private javax.swing.JTextField domicilioTF;
    private javax.swing.JButton eliminaB;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiarB;
    private javax.swing.JButton listarB;
    private javax.swing.JButton modificaB;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JTextField tarjetaTF;
    private javax.swing.JButton volverB;
    // End of variables declaration//GEN-END:variables
}
